---
title: "Posture Project"
author: "Giovani Gutierrez"
date: "2023-02-15"
output: 
  github_document:
    toc: true
    df_print: "kable"
    keep_html: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE,
                      tidy = TRUE,
                      fig.align = TRUE)

indent1 = '    '
indent2 = paste(rep(indent1, 2), collapse='')
indent3 = paste(rep(indent1, 3), collapse='')
```

# Getting Started

## Setup
```{r libraries}
library(tidyverse)
library(tidymodels)
library(readxl)
library(janitor)
library(visdat)
library(naniar)
library(corrplot)
tidymodels_prefer()

set.seed(123) # set seed
```

## Import Data
```{r read-in data}
data1 <- 
  read_xls('C:/Users/giova/Desktop/PSTAT 131/predicting_personality/Data/Posture_Data.xls') %>% 
  clean_names() # read in raw data from .xls file

data1 %>% 
  write.csv(file = 'C:/Users/giova/Desktop/PSTAT 131/predicting_personality/Data/raw_data.csv') # write raw data to .csv file

head(data1) # preview data
```

## Tidy Data & Missing Values
```{r missing values, fig.width = 10}
data1 <- 
  data1 %>% 
  replace_with_na_all(condition = ~.x == 'X') # replace 'X' character values with NA values

data1 %>% 
  vis_miss() # visualize missing values

data1 <- 
  data1 %>% 
  select(age:posture & -mbti) %>% 
  drop_na() # drop missing and irrelevant variables

data1 <- 
  data1 %>% 
  mutate(sex = factor(sex)) %>% 
  mutate(activity_level = ordered(activity_level,
                                  levels = c('Low', 'Moderate', 'High'))) %>% 
  mutate_at(c('pain_1', 'pain_2', 'pain_3', 'pain_4'), 
            as.numeric) %>% 
  mutate(e_i = factor(ifelse(e > i, 'extrovert', 'introvert'))) %>% 
  mutate_at(c('s', 'n', 't', 'f', 'j', 'p'), as.numeric) %>% 
  mutate(posture = factor(posture)) %>% 
  select(-e & -i) # coerce variables into appropriate type

data1 %>% 
  vis_dat() # visualize variable types

data1 %>% 
  write.csv(file = 'C:/Users/giova/Desktop/PSTAT 131/predicting_personality/Data/clean_data.csv') # write clean data to .csv file

head(data1) # preview cleaned data
```

*Describe variables here!*

# Exploratory Data Analysis (EDA)

## Correlation Between Features

```{r correlation plot}
data1 %>% 
  select_if(is.numeric) %>% 
  cor() %>% 
  corrplot(method = 'circle', 
           type = 'lower')
```

## Visual EDA
```{r visual eda}
ggplot(data = data1, aes(fill = e_i, x = e_i)) + 
  geom_bar()

ggplot(data = data1, aes(fill = sex, x = e_i)) + 
  geom_bar(position = "fill")

ggplot(data = data1, aes(fill = posture, x = e_i)) + 
  geom_bar(position = "fill")
```

